[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'rakr/vim-one'
hook_add = '''
  colorscheme one
  set background=dark
  let g:airline_theme='one'
'''

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  let g:airline_powerline_fonts = 1
  set laststatus=2
'''
